### ISSUE TITLE
GoScintilla GOSCI_Free crash in PB 5.6

### ISSUE THREAD

**Issue by MikeHart66** [tajmone/purebasic-archives#1]
Hi, 

your examples crash when call in GOSCI_FREE with PB5.6 when you change something in the example source code. 

Even simply changing a number will cause the app to crash when you close it.

**Comment by tajmone** [comment]
Thanks for reporting this. 

Can you provide more info on how to get a crash?

I've tried various example files with PB 5.60 (x64) and didn't experience any crashes. If you could help me reproduce the crash by providing the name of one of the example files, and paste here the line numbers and changes that cause the crash, it would be very helpful.

I haven't coded this library, I've just made a few tweaks to make it work with PB 5.60:

> GoScintilla was created by Stephen Rodriguez (aka @srod and nxSoftWare). The latest published version of GoScintilla 2 was version 2.7 (11th Aug 2012), which was no longer compatible with PureBASIC >= 5.10.

... so the original code was meant for PB 4.5 onwards. I need to check if there have been any language changes to PB since then that might affect the `GOSCI_Free()` procedure — but for this I need to reproduce the exact error you got.

The original GoScintilla announcement post on PB Forums is this:

- http://www.purebasic.fr/english/viewtopic.php?f=14&t=40088&hilit=go+scintilla

... in case you want to contact GoScintilla's  author to report the bug or to ask further questions.

**Comment by MikeHart66** [comment]
Thanks for the quick response. 
1) Run Demos/SimplePBSyntax/Demo_Simple1.pb in Debug mode. 
2) Click into the scintilla gadget and delete something or just press enter a few times. Or add a few empty lines at the end. 
3) Then you click on the Close button of the window (the X) and it crashes.

As soon as you change something or even fold something, it crashes for me when you close the window.

**Comment by tajmone** [comment]
I've tested it by compiling `Demo_Simple1.pb`:

- x86 with Debugger
- x86 without Debugger
- x64 with Debugger
- x64 without Debugger

I've encountered the crash you mention only with the 32 bit compiled binaries (with and without debugger on).

So at least now we have isolated the problem to the 32 bit area. I'll need some time to look at the source code to try and understand what brings about the crash — but my guess is that it has to do with memory management inside `GoScintilla.pbi`.

I did a quick test by adding some MessageRequesters inside `GOSCI_Free()`:

``` purebasic
Procedure GOSCI_Free(id)
  Protected *this._GoScintilla
  If IsGadget(id) And GadgetType(id) = #PB_GadgetType_Scintilla
    *this = GetGadgetData(id)
    If *this
      MessageRequester("DBG 1", "Before ClearStructure(*this, _GoScintilla)") ; <= DBG
      ClearStructure(*this, _GoScintilla)
      MessageRequester("DBG 2", "Before FreeMemory(*this)") ; <= DBG
      FreeMemory(*this)
    EndIf
    MessageRequester("DBG 3", "Before FreeGadget(id)") ; <= DBG
    FreeGadget(id)
  EndIf
EndProcedure
``` 

... MessageRequesters "DBG 1" and "DBG 2" show up before the crash, the 3rd one never shows up. So it looks like the crash occurs at `FreeMemory(*this)` instruction.

Somewhere in the code there must be some missing bitness checks for memory management.

I'll try to find some time to look into it — but can't promise anything right now because I'm trying to close a big project which is quite late behind. In any case, I'll post here any news on the bug search, and please do the same.

**Comment by tajmone** [comment]
**UPDATE**: I've notified **@srod** via PM of the issue, asked him if he can help ous out, and promised to update him if we find a fix for it.

**Comment by srod001** [comment]
Hi,

I have tried to reproduce this issue using PB 5.6 x86 with no luck. I cannot reproduce the crash.

The only thing I can say is that I am using my own version of GoScintilla as opposed to the one modified by Tristano, though I wouldn't have thought there would be much difference there. Am happy to email my version for you to try.

Stephen.

**Comment by MikeHart66** [comment]
I would love that. Btw. I am using the 64bit version of PB. Can you please sent it to 

xxx@xxx.de

**Comment by srod001** [comment]
Ah I was using the 32-bit version of PB ... no crash.

Just switched to the 64-bit version of PB... bang! Doesn't crash on the line you mention though.

Let me take a look.

**Comment by srod001** [comment]
Right,  switch the GOSCI_Free() procedure with the following to remove the crash I am seeing : 

```
Procedure GOSCI_Free(id)
  Protected *this._GoScintilla
  If IsGadget(id) And GadgetType(id) = #PB_GadgetType_Scintilla
    *this = GetGadgetData(id)
    FreeGadget(id)
    If *this
      ClearStructure(*this, _GoScintilla)
      FreeMemory(*this)
    EndIf
  EndIf
EndProcedure
```

**Comment by MikeHart66** [comment]
Thank you that works!

**Comment by tajmone** [comment]
Thanks a lot for your prompt support **@srod**!

I don't get any more crashes either (strange, I was getting crashes only with x86 binaries though)

I'll update the source files in the repository ASAP!

**Comment by tajmone** [comment]
Fixed:

https://github.com/tajmone/purebasic-archives/blob/master/pb-development/purelibs/scintilla/GoScintilla/HISTORY.md#v301-2017-09-08

... and bumped up version to 3.0.1.

Added thanks to @srod001 and @MikeHart66 in repo's history and commit message.
